<?php


namespace app\api\controller;


use app\BaseController;
use think\exception\HttpResponseException;

class ApiBase extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        // 允许的原域名

    }

    public function msg(...$args)
    {
        throw new HttpResponseException(msg(...$args));
    }

    public function isLogin()
    {
        $user = cache(config('redis.token_pre').$this->request->header('access-token'));
        if(!$user){
            return false;
        }
        if(!empty($user['id']) && !empty($user['nickname'])){
            return true;
        }
        return false;
    }
}