<?php


namespace app\api\controller;


use app\api\controller\ApiBase;

class AuthBase extends ApiBase
{
    public $userId = 0;
    public $username = '';
    public $accessToken = '74b71953244d0b391f6f54477fda2aff127d59ae';

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //$this->accessToken = $this->request->header('access-token');
        /*if(!$this->accessToken || !$this->isLogin()){
            return $this->msg(config('statusCode.not_login'),'没有登录');
        }else{
            $user = cache(config('redis.token_pre').$this->accessToken);
            $this->userId = $user['id'];
            $this->nickname = $user['nickname'];
        }*/

        $user = cache(config('redis.token_pre').$this->accessToken);
        if($user){
            $this->userId = $user['id'];
            $this->username = isset($user['phone']) ? $user['phone'] : $user['username'];
        }

    }

    /*public function isLogin()
    {
        $user = cache(config('redis.token_pre').$this->accessToken);
        if(!$user){
            return false;
        }
        if(!empty($user['id']) && !empty($user['nickname'])){
            $this->userId = $user['id'];
            $this->nickname = $user['nickname'];
            return true;
        }
        return false;
    }*/
}