<?php


namespace app\api\controller;



use app\BaseController;
use app\Request;
use app\api\validate\SmsValidate;
use app\common\business\UserBusiness;
use think\Exception;
use think\exception\HttpResponseException;

class Login extends AuthBase
{
    /*public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if($this->isLogin()){
            return $this->msg(config('statusCode.is_login'),'已经登录');
        }
    }*/
    public function index(){
        return 'index';
    }
    public function msg(...$arg)
    {
        throw new HttpResponseException(msg($arg[0],$arg[1]));
    }
    public function login(Request $request)
    {
        $code = $request->param('code','','trim');
        $phone = $request->param('phone_number','','trim');
        $ltype = $request->param('ltype',1,'intval');
        $stype = $request->param('stype',0,'intval');
        $key = $request->param('code_key','verificationCode_PevHANNamLDzOiT','trim');
        $username = $request->param('username','','trim');
        $password = $request->param('password','','trim');

        $loginValidate = new SmsValidate();
        if($ltype == 1) {
            $data = [
                'phone_number' => $phone,
                'code' => $code,
                'ltype' => $ltype,
                'stype' => $stype,
                'code_key' => $key,
            ];
            $validate = $loginValidate->scene('phone_login')->check($data);
        }else{
            $data = [
                'username' => $username,
                'password' => $password,
                'ltype' => $ltype,
                'stype' => $stype,
            ];
            $validate = $loginValidate->scene('login')->check($data);
        }


        if(!$validate){
            return msg(config('statusCode.error'),$loginValidate->getError());
        }
        try {
            $res = (new UserBusiness())->login($data);
        }catch (Exception $e){
            return msg($e->getCode(),$e->getMessage());
        }

        if($res){
            return msg(config('statusCode.success'),'登录成功',$res);
        }
        return msg(config('statusCode.error'),'登录失败',$res,401);
    }
}